services:
  my-app:
    build: .
    container_name: my-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./images:/app/images
    command: ["/bin/sh", "-c", "python -m alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"]
